"""
DashUI — shared ipywidgets component library for the Dashlibs suite.
Import from here in any dash-* package instead of duplicating widget code.
"""
from dashui.components import (
    EditableTable,
    EnvSetupPanel,
    SourceSelector,
    action_button,
    card,
    editable_table,
    env_setup_panel,
    header,
    html,
    output_panel,
    running_list,
    section,
    source_selector,
    status_line,
)
from dashui.persistence import (
    clear_config_dir,
    config_path,
    get_config_dir,
    load_config,
    save_config,
    set_config_dir,
)
from dashui.schema import list_columns, list_columns_safe
from dashui.theme import (
    ACCENT_BG,
    ACCENT_FG,
    BORDER,
    BORDER_STRONG,
    CARD,
    DANGER,
    FONT_MONO,
    FONT_SANS,
    INFO,
    MUTED,
    PRIMARY,
    SUCCESS,
    WARNING,
    accent,
)

__version__ = "0.3.1"
__all__ = [
    "SourceSelector",
    "EditableTable",
    "EnvSetupPanel",
    "action_button",
    "card",
    "editable_table",
    "env_setup_panel",
    "header",
    "html",
    "output_panel",
    "running_list",
    "section",
    "source_selector",
    "status_line",
    "list_columns",
    "list_columns_safe",
    "get_config_dir",
    "set_config_dir",
    "clear_config_dir",
    "config_path",
    "load_config",
    "save_config",
    "accent",
    "PRIMARY",
    "SUCCESS",
    "DANGER",
    "WARNING",
    "INFO",
    "BORDER",
    "BORDER_STRONG",
    "CARD",
    "MUTED",
    "ACCENT_BG",
    "ACCENT_FG",
    "FONT_SANS",
    "FONT_MONO",
]
